### PR TITLE
feat(map.jinja): update to template standards

### PR DESCRIPTION
**Pull request by baby-gnu**
The previous “map.jinja” had several issues:

- the “os_family” map was named “osmap” which was confusing

- the settings merge order was inverted, “os_family” settings was
  overriding “oscodename” ones.

BREAKING CHANGE: use “osfinger” instead of “oscodename” to override
configuration per distribution version.

* libvirt/map.jinja: update to “template-formula” standard.

* libvirt/osfamilymap.yaml: fix the name for the “os_family” settings.

* libvirt/osmap.yaml: empty per OS name settings for now.

* libvirt/osfingermap.yaml: replace “oscodename” overrides.
  Set some settings for older Debian and Ubuntu releases.

### CODE REVIEW

**Comment by baby-gnu** [comment]
Hello.

With this, I'll be able to start adding more supported platforms, at least the Python3 ones.

Thanks.

**Comment by myii** [comment]
@baby-gnu I like the look of this, thanks. I'll look at this properly when I get a chance and get back to you.

**Comment by baby-gnu** [comment]
@myii thanks a lot. It's not yet vacations for me but I can spend some time on this formula.

**Comment by daks** [comment]
Just a quick eye-only review, but it looks good to me too

**Comment by myii** [comment]
Thanks @baby-gnu, this has been merged.  Also thanks to both @aboe76 and @daks for the feedback.

**Pull request merged**
