### PR TITLE
Feature/add kitchen tests

### PR DESCRIPTION
**Pull request by baby-gnu**

### CODE REVIEW

**Comment by aboe76** [comment]
@baby-gnu only #34 didn't fix the problem...

**Comment by baby-gnu** [comment]
@aboe76 yes, we need to check for `salt['grains.get']('pythonversion')[0] == 3`.

I plan to fix that after this PR merged.

**Comment by baby-gnu** [comment]
I finally managed to understand how to skip the admin socket for older `libvirtd`.

I needed dedicated custom resources to `return skip_resource` from the `initialize` method.

Good to merge for me.

Regards.

**Comment by baby-gnu** [comment]
Could it be merged?

**Comment by myii** [comment]
@baby-gnu We really need all of the tests passing.  Or if something needs to be fixed in the CI, that needs to be done first.  Common error:

```salt
                 ID: libvirt.keys
           Function: virt.keys
               Name: libvirt_keys
             Result: False
            Comment: State 'virt.keys' was not found in SLS 'libvirt.keys'
              Reason: 'virt' __virtual__ returned False
```

**Comment by baby-gnu** [comment]
> We really need all of the tests passing. Or if something needs to be fixed in the CI, that needs to be done first.

Ok, I was wondering in which order to do the job.

**Comment by baby-gnu** [comment]
I'll fix tests to pass after merging #36 ad #37.

**Comment by baby-gnu** [comment]
I'll disable `centos-6` because of the python version problem: SaltStack is installed with python-2.7 but the system is python-2.6, so we have an issue when installing the `libvirt-python` library.

**Comment by myii** [comment]
@baby-gnu I've merged #35, #36 and #37 in my own fork for testing in Travis but we're still getting failures: https://travis-ci.org/myii/libvirt-formula/builds/544406124.  You can use the link on that page to confirm that I've applied your changes correctly (but there were no conflicts).  How would you like to proceed?

**Comment by baby-gnu** [comment]
Hello @myii.

Sorry, I think I did the whole thing in the wrong order.

Ideally, I should have done several branches to apply in the order to make it easier to follow

1. initialize the kitchen tests with only 1 test on 1 platform
   1. write the test
   2. fix the forumla if required (like with the python package problem)
2. for each formula feature
   1. add a test for the only available platform
   2. fix the formula if required
3. for each wanted supported platform
   1. adapt the test when required
   2. fix the formula

Now:

* I could redo the complete thing the way I describe above if you want
* I could close without merging #36 and #37 and apply the changes directly in this pull request

**Comment by myii** [comment]
@baby-gnu That's a good idea, let's get this all up and running with even one platform and then expand it from there.  I'll let you decide how you would prefer to proceed.  It's OK if you want the other PRs merged first or do it all in one.

**Comment by baby-gnu** [comment]
Great, this branch is now ready to be merged for me, I'm planning the other branches.

**Comment by baby-gnu** [comment]
Hello @myii 

So I finished to push the single platform tests, each one based on the previous:

1. verify the options of `libvirtd.conf` (#38)
2. verify the installed packages (#39)
3. verify running service (#40)
4. verify the `libvirtd` sockets (#41)

When they will be merged, I'll start to enable other platforms.

Regards.

**Comment by aboe76** [comment]
@myii shall I merge this one?

**Comment by baby-gnu** [comment]
Hello.

> @myii shall I merge this one?

I'm waiting for the merge of this one and #38 #39 #40 #41 before continuing. I'll add you as reviewer of all of them.

Regards.

**Comment by aboe76** [comment]
@baby-gnu merged it so you can continue with you great work!

**Comment by baby-gnu** [comment]
@aboe76 ok, I'll merge everything.

Thanks.

**Pull request merged**
