### PR TITLE
Use virt.keys to get compatible with Salt >= 2016.3.0.

### PR DESCRIPTION
**Pull request by ukretschmer**

### CODE REVIEW

**Comment by babilen** [comment]
This would break on salt versions earlier than 2016.3.0 though. It is probably necessary to use different names depending on the salt version.

**Comment by ukretschmer** [comment]
Yes it will break. I'll implement your suggested solution for backward compatibility and pull request again.

**Comment by babilen** [comment]
Wonderful, thank you!

**Comment by gravyboat** [comment]
Changes look good for backwards compatiblity, thank you.

**Pull request merged**
