### PR TITLE
docs(readme): fix `template` to `libvirt` under `bin/kitchen converge`

### PR DESCRIPTION
**Pull request by myii**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [x] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
Comment about the `CODEOWNERS` test performed here:

* Started with a basic version of the file, without a global owner:
  - https://github.com/saltstack-formulas/libvirt-formula/blob/614f2e27f7de7e9f74dcbc958bb317682293b4fd/CODEOWNERS
* Sent this PR through, no reviewer assigned (naturally)
* (Probably didn't need this stage) Made this a draft PR
* Updated the `CODEOWNERS` to set @baby-gnu as the global owner:
  - https://github.com/saltstack-formulas/libvirt-formula/blob/db8420b599d05d61e88a0d16a939bf251a141aae/CODEOWNERS
* Rebased this PR and force pushed -- no change immediately due to draft status
* Unset draft status and it automatically selected @baby-gnu -- so working as expected

Also tested with #75 in-between and all picking up fine.

**Comment by myii** [comment]
Hey @baby-gnu, thanks for the review.  Aren't you going to merge it?  I see from the `CODEOWNERS` file that you're the only global owner here!!

**Comment by baby-gnu** [comment]
> Hey @baby-gnu, thanks for the review. Aren't you going to merge it? I see from the `CODEOWNERS` file that you're the only global owner here!!

I was waiting for the tests to finish and I started something else so it took time to come back here ;-)

**Comment by myii** [comment]
> I was waiting for the tests to finish and I started something else so it took time to come back here ;-)

Actually, I saw another GitHub bot/action available for that, so that you can hit merge and it will do it automatically once the tests complete.  Should we enable something like that?

**Comment by baby-gnu** [comment]
> Should we enable something like that?

So the merge is blocked by failing tests? I think it could be a good thing.

**Comment by myii** [comment]
> So the merge is blocked by failing tests? I think it could be a good thing.

I've collected the list of available GitHub Actions or bots:

* https://tree.taiga.io/project/myii-saltstack-formulas/task/197

We can go through them over time to see which ones we fancy testing.

**Pull request merged**
